### ISSUE TITLE
SaaS app to allow people to build their own E-commerce applications.

### ISSUE THREAD

**Issue by woodssx** [woodssx/Modern-Cloud#1]
Lex and Stephanie had the great idea of building a SaaS app to allow people to build their own E-commerce apps. They named their project the Modern Cloud. This will be their first start-up. They decided to use GitHub as the central repository in which their work was going to be stored. The Modern Cloud project will be bootstrapped by Lex and Stephanie. They will use their own savings and work in their own home garage.

**Comment by Lex-Locke7** [comment]
Ready to start working!
